### ISSUE TITLE
Please provide the classification model

### ISSUE THREAD

**Issue by zqx1609** [arjunpatel7/perfect-prompt#13]
Hi, I have run your code ,but when I pass the prompt I got a bug here:
```
Traceback (most recent call last):
  File "/home/zqx/anaconda3/envs/py37/lib/python3.7/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/zqx/文档/experiment/perfect-prompt/app.py", line 168, in <module>
    button_click = st.button('Generate Variations', on_click=make_and_grade_variations(df, input_prompt=input))
  File "/home/zqx/文档/experiment/perfect-prompt/app.py", line 77, in make_and_grade_variations
    keyword = classify_prompts(df, [input_prompt]).classifications[0].prediction
  File "/home/zqx/文档/experiment/perfect-prompt/app.py", line 51, in classify_prompts
    response = co.classify(model='40e50ea7-0586-4f53-ab2d-96296048993f-ft',inputs=prompts)
  File "/home/zqx/anaconda3/envs/py37/lib/python3.7/site-packages/cohere/client.py", line 295, in classify
    response = self.__request(cohere.CLASSIFY_URL, json=json_body)
  File "/home/zqx/anaconda3/envs/py37/lib/python3.7/site-packages/cohere/client.py", line 522, in __request
    headers=response.headers,
cohere.error.CohereError: model not found
```
It seems that you trained a custom model and I don't have it, So could you send me the model?

**Comment by arjunpatel7** [comment]
Hello @zqx1609 ! Thanks for leaving an issue. I realize that the repo in its current state doesn't lend well to reproducing on your own. I don't think there is a way for me to surface the model like you describe, but I can probably write a training script with the data I used so that you may reproduce the model with your own Cohere account. Would that work for you? Thanks in advance!
